feat: created shortcut manager as standalone package
webbeetechnologies/bamboo-molecules pull request #262
Opened 2023-09-12 10:00 UTC by thetaungg

2023-09-12 12:06 UTC, shashank1010 requested changes

2023-09-16 07:52 UTC, elvisduru submitted a review, later dismissed

2023-09-16 09:20 UTC, shashank1010 requested changes
- [ ] Allow to disable a shortcut with the hook itself instead of handling it in the callback.
- [ ] If shortcuts are disabled, event should not be prevented. (currently default events are just prevented)

2023-09-16 11:40 UTC, thetaungg commented on src/shortcuts-manager/useShortcut/useShortcut.tsx
> +        if (Platform.OS !== 'web') return;
removed

2023-09-16 11:49 UTC, shashank1010 approved these changes
Great Job!!

2023-09-16 11:49 UTC, merged